export type JsonValue = string | number | boolean | null | JsonObject | JsonValue[];
/**
 * // TODO: Reduce duplication with `JSON` type generated by https://supabase.com/docs/guides/api/rest/generating-types
 */
export interface JsonObject {
  [key: string]: JsonValue;
}

type Primitive = string | number | boolean | null;

export type FlatJson = Record<string, Primitive>;

export type Model = {
  back_seat_folds_flat?: boolean | null;
  concern?: string | null;
  /**
   * Using ISO string format for the timestamp
   */
  created_at: string;
  id: number;
  make: string;
  model: string;
  note?: string | null;
  trim: string;
  year: number;
};

export type ScrapedListing = {
  make: string;
  model: string;
  trim: string;
  year: number;
} & Database['public']['Tables']['listings']['Row'];
