CREATE TABLE public.models(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    year integer NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    trim text NOT NULL DEFAULT ''::text,
    back_seat_folds_flat boolean NULL,
    note text NULL,
    concern text NULL,
    CONSTRAINT models_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS unique_year_make_model_trim_idx ON public.models USING btree(year, lower(trim(BOTH FROM make)), lower(trim(BOTH FROM model)), lower(trim(BOTH FROM ""trim""))) TABLESPACE pg_default;

