-- public.models definition
-- Drop table
-- DROP TABLE public.models;
CREATE TABLE public.models(
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    "year" int4 NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    trim text DEFAULT ''::text NOT NULL,
    back_seat_folds_flat bool NULL,
    note text NULL,
    concern text NULL,
    lowercase_hash text NOT NULL,
    CONSTRAINT models_lowercase_hash_key UNIQUE (lowercase_hash),
    CONSTRAINT models_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX unique_year_make_model_trim_idx ON public.models USING btree(year, lower(TRIM(BOTH FROM make)), lower(TRIM(BOTH FROM model)), lower(TRIM(BOTH FROM "trim")));

